on:
    pull_request: 
        types: 
            - opened

jobs:
    testing-actions:
        runs-on: [ self-hosted,Linux,X64,prod,main ]
        permissions: 
            issues: write
            pull-requests: write

        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3


            - name: Post PR Comment
              uses: ./
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  giphy-api-key: ${{ secrets.GIPHY_API_KEY }}




                  
